### ISSUE TITLE
Error when installed globally, not in .venv

### ISSUE THREAD

**Issue by StephanKuempel** [useblocks/sphinx-performance#11]
When installing globally on Windows without environment
```
pip install sphinx-performance
```
-> on running sphinx-performance there is the following error
...
File "c:\users\kuempel\appdata\local\programs\python\python39\lib\site-packages\sphinx_performance\projectenv.py", line 250, in install_dependencies
    subprocess.call(dep_command, stdout=subprocess.DEVNULL)

It seem like the correct paths are not calculated correctly.

**Comment by danwos** [comment]
Thanks for the bug report.

Is in the logs also an Exception type or a traceback mentioned?

I can only guess, but maybe the ``pip`` command is not in the same folder as the ``python`` command.
Or some rights are missing. Tough one...

**Comment by StephanKuempel** [comment]
Full stack trace here:

Traceback (most recent call last):
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\kuempel\AppData\Local\Programs\Python\Python39\Scripts\sphinx-performance.exe\__main__.py", line 4, in <module>
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\site-packages\sphinx_performance\main.py", line 213, in <module>
    cli()
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\site-packages\sphinx_performance\main.py", line 113, in cli
    project.install_dependencies()
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\site-packages\sphinx_performance\projectenv.py", line 250, in install_dependencies
    subprocess.call(dep_command, stdout=subprocess.DEVNULL)
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\kuempel\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by StephanKuempel** [comment]
python.exe and pip.exe are located here (default on Windows ?)

"C:\Users\kuempel\AppData\Local\Programs\Python\Python39\python.exe"
"C:\Users\kuempel\AppData\Local\Programs\Python\Python39\Scripts\pip.exe"

**Comment by danwos** [comment]
I have published a fix on the "main" branch.
I hope this fixes the problem for all uses cases.

Can you please give it a try by installing it from sources?

Thanks.

**Comment by StephanKuempel** [comment]
Sorry for the late response. It's not working, since your check is looking for pip only (it's pip.exe on windows)

FileNotFoundError: Could not found "pip" in calculated path: c:\users\kuempel\appdata\local\programs\python\python39\Scripts\pip
