### ISSUE TITLE
No such file or directory: 'snakeviz'

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinx-performance#5]
Running this 
```
sphinx-performance --parallel 4 --pages 20 --dummies 200 --snakeviz --profile foo
```
leads to
```
Starting snakeviz servers

Traceback (most recent call last):
  File "/home/marco/ub/sphinx-performance/.venv/bin/sphinx-performance", line 2, in <module>
    from sphinx_performance.main import cli
  File "/home/marco/ub/sphinx-performance/sphinx_performance/main.py", line 143, in <module>
    cli()
  File "/home/marco/ub/sphinx-performance/.venv/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/marco/ub/sphinx-performance/.venv/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/marco/ub/sphinx-performance/.venv/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/marco/ub/sphinx-performance/.venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/marco/ub/sphinx-performance/.venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/marco/ub/sphinx-performance/sphinx_performance/main.py", line 133, in cli
    proc = subprocess.Popen(["snakeviz", f"profile/{p}.prof"])
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'snakeviz'
```

**Comment by danwos** [comment]
See #7. Need some time to provide this feature.

**Comment by danwos** [comment]
Done via ``sphinx-analysis`` now, and snakeviz is a dependency now.
